### ISSUE TITLE
Does nodejs-serialport build on maser version and on dunfell?

### ISSUE THREAD

**Issue by andershedberg** [axians/meta-microservicebus#44]
Hi, I don't seem to be able to incorporate the master branch to build nodejs-serialport on a system that has moved to Yocto dunfell verison. Just adding dunfell to the LAYERDEPENDS_xxx does not seem to work. It seems that nodejs-serialport does not exist on the master branch? But it is still mentioned in the readme-files... 

When building the system it fails with ( or similar for nodejs-serialport ): 

ERROR: Nothing RPROVIDES 'packagegroup-microservice-extra'

Please help as I am confused after an 12 hour pass to try to get it working...

**Comment by jonaskgandersson** [comment]
Hi, meta-microservicebus have not been tested with Yocto Dunfell.
Since Yocto Zeus(currently master) nodejs-serialport have removed because microservicebus -node have no dependency to it. Microservicebus will fetch serialport from npm if needed, you may need to add "packagegroup-microservice-build" as node-gyp use make and gcc to build native addons. 

The readme file is out of date and I will update it.

To fix your error you need to remove "packagegroup-microservice-extra" from your build config. If you have any specific need to add nodejs-serialport at build time we can certainly help you. But you may get other errors when building with Yocto Dunfell.

If you have an need to build for Yocto Dunfell I can check what it will take to update the layer.

**Comment by andershedberg** [comment]
Thanks for the reply. I mainly need to enable the usb-to-serial-port on a raspberry pi running https://github.com/brocaar/chirpstack-gateway-os and node-red. It was possible before @brocaar updated to Dunfell. 
I really have no idea what I'm doing, and now the sd-card build steps failed when I changed to "packagegroup-microservice-build", but I can't figure out if that was at all related so I restart from scratch and will try to get some other way to get a working serial port.

**Comment by jonaskgandersson** [comment]
Okay, microservicebus have no connection to https://github.com/brocaar/chirpstack-gateway-os so I suggest you open an issue on chirpstack.
